name: doc

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
        git config --global user.email "${{secrets.EMAIL}}"
        git config --global user.name "${{secrets.USER_NAME}}"

      - run: |
        yarn deploy

