name: doc

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    uses: actions/checkout
    steps:
      - run: |
        git config --global user.email "${{secrets.EMAIL}}"
        git config --global user.name "${{secrets.USER_NAME}}"
        yarn build
